# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'college',
            },
        ),
        migrations.CreateModel(
            name='DetailGradeInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_num', models.IntegerField(default=0)),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.CollegeInformation', to_field='college_name')),
            ],
            options={
                'db_table': 'user_grade',
            },
        ),
        migrations.CreateModel(
            name='GradeInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='IdentityInformation',
            fields=[
                ('role_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'identity',
            },
        ),
        migrations.CreateModel(
            name='MajorInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'major',
            },
        ),
        migrations.CreateModel(
            name='SignInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_time', models.DateTimeField(auto_now_add=True)),
                ('initiator', models.IntegerField()),
                ('reached', models.IntegerField()),
                ('actual', models.IntegerField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.DetailGradeInformation')),
            ],
            options={
                'db_table': 'sign',
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.BooleanField()),
                ('first_create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modify_time', models.DateTimeField(auto_now=True)),
                ('new_sign', models.BooleanField(default=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.DetailGradeInformation')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.IdentityInformation')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='detailgradeinformation',
            name='grade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.GradeInformation', to_field='grade_name'),
        ),
        migrations.AddField(
            model_name='detailgradeinformation',
            name='major_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.MajorInformation', to_field='major_name'),
        ),
    ]
